EXPORT_LOCAL_PATH :=  $(call my-dir)
$(info "$(EXPORT_LOCAL_PATH)")
SELF_LOCAL_EXPORT_C_INCLUDES:= 
SELF_LOCAL_EXPORT_SRC_FILES := 
SELF_LOCAL_EXPORT_LDLIBS    := 
include $(EXPORT_LOCAL_PATH)/../../export_template.mk