// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers/ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class Conversation;
@class ConversationBuilder;
@class ConversationListRequest;
@class ConversationListRequestBuilder;
@class ConversationListResponse;
@class ConversationListResponseBuilder;
@class HelloRequest;
@class HelloRequestBuilder;
@class HelloResponse;
@class HelloResponseBuilder;


typedef NS_ENUM(SInt32, CmdID) {
  CmdIDCmdIdInvalid = -1,
  CmdIDCmdIdUnknown = 0,
  CmdIDCmdIdHello = 1,
  CmdIDCmdIdAuth = 2,
  CmdIDCmdIdSendMessage = 3,
  CmdIDCmdIdConversationList = 4,
  CmdIDCmdIdJointopic = 5,
  CmdIDCmdIdLefttopic = 7,
};

BOOL CmdIDIsValidValue(CmdID value);
NSString *NSStringFromCmdID(CmdID value);

typedef NS_ENUM(SInt32, ConversationListRequestFilterType) {
  ConversationListRequestFilterTypeDefault = 0,
  ConversationListRequestFilterTypeAll = 1,
  ConversationListRequestFilterTypeNearBy = 2,
  ConversationListRequestFilterTypeFriends = 3,
  ConversationListRequestFilterTypeHot = 4,
};

BOOL ConversationListRequestFilterTypeIsValidValue(ConversationListRequestFilterType value);
NSString *NSStringFromConversationListRequestFilterType(ConversationListRequestFilterType value);


@interface MainRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define HelloRequest_user @"user"
#define HelloRequest_text @"text"
@interface HelloRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasUser_:1;
  BOOL hasText_:1;
  NSString* user;
  NSString* text;
}
- (BOOL) hasUser;
- (BOOL) hasText;
@property (readonly, strong) NSString* user;
@property (readonly, strong) NSString* text;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HelloRequestBuilder*) builder;
+ (HelloRequestBuilder*) builder;
+ (HelloRequestBuilder*) builderWithPrototype:(HelloRequest*) prototype;
- (HelloRequestBuilder*) toBuilder;

+ (HelloRequest*) parseFromData:(NSData*) data;
+ (HelloRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloRequest*) parseFromInputStream:(NSInputStream*) input;
+ (HelloRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HelloRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HelloRequestBuilder : PBGeneratedMessageBuilder {
@private
  HelloRequest* resultHelloRequest;
}

- (HelloRequest*) defaultInstance;

- (HelloRequestBuilder*) clear;
- (HelloRequestBuilder*) clone;

- (HelloRequest*) build;
- (HelloRequest*) buildPartial;

- (HelloRequestBuilder*) mergeFrom:(HelloRequest*) other;
- (HelloRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HelloRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUser;
- (NSString*) user;
- (HelloRequestBuilder*) setUser:(NSString*) value;
- (HelloRequestBuilder*) clearUser;

- (BOOL) hasText;
- (NSString*) text;
- (HelloRequestBuilder*) setText:(NSString*) value;
- (HelloRequestBuilder*) clearText;
@end

#define HelloResponse_retcode @"retcode"
#define HelloResponse_errmsg @"errmsg"
@interface HelloResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRetcode_:1;
  BOOL hasErrmsg_:1;
  SInt32 retcode;
  NSString* errmsg;
}
- (BOOL) hasRetcode;
- (BOOL) hasErrmsg;
@property (readonly) SInt32 retcode;
@property (readonly, strong) NSString* errmsg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (HelloResponseBuilder*) builder;
+ (HelloResponseBuilder*) builder;
+ (HelloResponseBuilder*) builderWithPrototype:(HelloResponse*) prototype;
- (HelloResponseBuilder*) toBuilder;

+ (HelloResponse*) parseFromData:(NSData*) data;
+ (HelloResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloResponse*) parseFromInputStream:(NSInputStream*) input;
+ (HelloResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (HelloResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (HelloResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface HelloResponseBuilder : PBGeneratedMessageBuilder {
@private
  HelloResponse* resultHelloResponse;
}

- (HelloResponse*) defaultInstance;

- (HelloResponseBuilder*) clear;
- (HelloResponseBuilder*) clone;

- (HelloResponse*) build;
- (HelloResponse*) buildPartial;

- (HelloResponseBuilder*) mergeFrom:(HelloResponse*) other;
- (HelloResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (HelloResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRetcode;
- (SInt32) retcode;
- (HelloResponseBuilder*) setRetcode:(SInt32) value;
- (HelloResponseBuilder*) clearRetcode;

- (BOOL) hasErrmsg;
- (NSString*) errmsg;
- (HelloResponseBuilder*) setErrmsg:(NSString*) value;
- (HelloResponseBuilder*) clearErrmsg;
@end

#define Conversation_topic @"topic"
#define Conversation_notice @"notice"
#define Conversation_name @"name"
@interface Conversation : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTopic_:1;
  BOOL hasNotice_:1;
  BOOL hasName_:1;
  NSString* topic;
  NSString* notice;
  NSString* name;
}
- (BOOL) hasTopic;
- (BOOL) hasNotice;
- (BOOL) hasName;
@property (readonly, strong) NSString* topic;
@property (readonly, strong) NSString* notice;
@property (readonly, strong) NSString* name;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConversationBuilder*) builder;
+ (ConversationBuilder*) builder;
+ (ConversationBuilder*) builderWithPrototype:(Conversation*) prototype;
- (ConversationBuilder*) toBuilder;

+ (Conversation*) parseFromData:(NSData*) data;
+ (Conversation*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Conversation*) parseFromInputStream:(NSInputStream*) input;
+ (Conversation*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Conversation*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Conversation*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConversationBuilder : PBGeneratedMessageBuilder {
@private
  Conversation* resultConversation;
}

- (Conversation*) defaultInstance;

- (ConversationBuilder*) clear;
- (ConversationBuilder*) clone;

- (Conversation*) build;
- (Conversation*) buildPartial;

- (ConversationBuilder*) mergeFrom:(Conversation*) other;
- (ConversationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConversationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasTopic;
- (NSString*) topic;
- (ConversationBuilder*) setTopic:(NSString*) value;
- (ConversationBuilder*) clearTopic;

- (BOOL) hasNotice;
- (NSString*) notice;
- (ConversationBuilder*) setNotice:(NSString*) value;
- (ConversationBuilder*) clearNotice;

- (BOOL) hasName;
- (NSString*) name;
- (ConversationBuilder*) setName:(NSString*) value;
- (ConversationBuilder*) clearName;
@end

#define ConversationListRequest_access_token @"accessToken"
#define ConversationListRequest_type @"type"
@interface ConversationListRequest : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasType_:1;
  BOOL hasAccessToken_:1;
  SInt32 type;
  NSString* accessToken;
}
- (BOOL) hasAccessToken;
- (BOOL) hasType;
@property (readonly, strong) NSString* accessToken;
@property (readonly) SInt32 type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConversationListRequestBuilder*) builder;
+ (ConversationListRequestBuilder*) builder;
+ (ConversationListRequestBuilder*) builderWithPrototype:(ConversationListRequest*) prototype;
- (ConversationListRequestBuilder*) toBuilder;

+ (ConversationListRequest*) parseFromData:(NSData*) data;
+ (ConversationListRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConversationListRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ConversationListRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConversationListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ConversationListRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConversationListRequestBuilder : PBGeneratedMessageBuilder {
@private
  ConversationListRequest* resultConversationListRequest;
}

- (ConversationListRequest*) defaultInstance;

- (ConversationListRequestBuilder*) clear;
- (ConversationListRequestBuilder*) clone;

- (ConversationListRequest*) build;
- (ConversationListRequest*) buildPartial;

- (ConversationListRequestBuilder*) mergeFrom:(ConversationListRequest*) other;
- (ConversationListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConversationListRequestBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAccessToken;
- (NSString*) accessToken;
- (ConversationListRequestBuilder*) setAccessToken:(NSString*) value;
- (ConversationListRequestBuilder*) clearAccessToken;

- (BOOL) hasType;
- (SInt32) type;
- (ConversationListRequestBuilder*) setType:(SInt32) value;
- (ConversationListRequestBuilder*) clearType;
@end

#define ConversationListResponse_list @"list"
@interface ConversationListResponse : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * listArray;
}
@property (readonly, strong) NSArray<Conversation*> * list;
- (Conversation*)listAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ConversationListResponseBuilder*) builder;
+ (ConversationListResponseBuilder*) builder;
+ (ConversationListResponseBuilder*) builderWithPrototype:(ConversationListResponse*) prototype;
- (ConversationListResponseBuilder*) toBuilder;

+ (ConversationListResponse*) parseFromData:(NSData*) data;
+ (ConversationListResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConversationListResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ConversationListResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ConversationListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ConversationListResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ConversationListResponseBuilder : PBGeneratedMessageBuilder {
@private
  ConversationListResponse* resultConversationListResponse;
}

- (ConversationListResponse*) defaultInstance;

- (ConversationListResponseBuilder*) clear;
- (ConversationListResponseBuilder*) clone;

- (ConversationListResponse*) build;
- (ConversationListResponse*) buildPartial;

- (ConversationListResponseBuilder*) mergeFrom:(ConversationListResponse*) other;
- (ConversationListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ConversationListResponseBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray<Conversation*> *)list;
- (Conversation*)listAtIndex:(NSUInteger)index;
- (ConversationListResponseBuilder *)addList:(Conversation*)value;
- (ConversationListResponseBuilder *)setListArray:(NSArray<Conversation*> *)array;
- (ConversationListResponseBuilder *)clearList;
@end


// @@protoc_insertion_point(global_scope)
