// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

#ifndef PROTOBUF_main_2eproto__INCLUDED
#define PROTOBUF_main_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace com {
namespace tencent {
namespace mars {
namespace sample {
namespace proto {
class Conversation;
class ConversationDefaultTypeInternal;
extern ConversationDefaultTypeInternal _Conversation_default_instance_;
class ConversationListRequest;
class ConversationListRequestDefaultTypeInternal;
extern ConversationListRequestDefaultTypeInternal _ConversationListRequest_default_instance_;
class ConversationListResponse;
class ConversationListResponseDefaultTypeInternal;
extern ConversationListResponseDefaultTypeInternal _ConversationListResponse_default_instance_;
class HelloRequest;
class HelloRequestDefaultTypeInternal;
extern HelloRequestDefaultTypeInternal _HelloRequest_default_instance_;
class HelloResponse;
class HelloResponseDefaultTypeInternal;
extern HelloResponseDefaultTypeInternal _HelloResponse_default_instance_;
}  // namespace proto
}  // namespace sample
}  // namespace mars
}  // namespace tencent
}  // namespace com

namespace com {
namespace tencent {
namespace mars {
namespace sample {
namespace proto {

namespace protobuf_main_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_main_2eproto

enum ConversationListRequest_FilterType {
  ConversationListRequest_FilterType_DEFAULT = 0,
  ConversationListRequest_FilterType_ALL = 1,
  ConversationListRequest_FilterType_NEAR_BY = 2,
  ConversationListRequest_FilterType_FRIENDS = 3,
  ConversationListRequest_FilterType_HOT = 4
};
bool ConversationListRequest_FilterType_IsValid(int value);
const ConversationListRequest_FilterType ConversationListRequest_FilterType_FilterType_MIN = ConversationListRequest_FilterType_DEFAULT;
const ConversationListRequest_FilterType ConversationListRequest_FilterType_FilterType_MAX = ConversationListRequest_FilterType_HOT;
const int ConversationListRequest_FilterType_FilterType_ARRAYSIZE = ConversationListRequest_FilterType_FilterType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConversationListRequest_FilterType_descriptor();
inline const ::std::string& ConversationListRequest_FilterType_Name(ConversationListRequest_FilterType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConversationListRequest_FilterType_descriptor(), value);
}
inline bool ConversationListRequest_FilterType_Parse(
    const ::std::string& name, ConversationListRequest_FilterType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConversationListRequest_FilterType>(
    ConversationListRequest_FilterType_descriptor(), name, value);
}
enum CmdID {
  CMD_ID_INVALID = -1,
  CMD_ID_UNKNOWN = 0,
  CMD_ID_HELLO = 1,
  CMD_ID_AUTH = 2,
  CMD_ID_SEND_MESSAGE = 3,
  CMD_ID_CONVERSATION_LIST = 4,
  CMD_ID_JOINTOPIC = 5,
  CMD_ID_LEFTTOPIC = 7,
  CMD_ID_PUSH = 10001
};
bool CmdID_IsValid(int value);
const CmdID CmdID_MIN = CMD_ID_INVALID;
const CmdID CmdID_MAX = CMD_ID_PUSH;
const int CmdID_ARRAYSIZE = CmdID_MAX + 1;

const ::google::protobuf::EnumDescriptor* CmdID_descriptor();
inline const ::std::string& CmdID_Name(CmdID value) {
  return ::google::protobuf::internal::NameOfEnum(
    CmdID_descriptor(), value);
}
inline bool CmdID_Parse(
    const ::std::string& name, CmdID* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CmdID>(
    CmdID_descriptor(), name, value);
}
// ===================================================================

class HelloRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.HelloRequest) */ {
 public:
  HelloRequest();
  virtual ~HelloRequest();

  HelloRequest(const HelloRequest& from);

  inline HelloRequest& operator=(const HelloRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloRequest& default_instance();

  static inline const HelloRequest* internal_default_instance() {
    return reinterpret_cast<const HelloRequest*>(
               &_HelloRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(HelloRequest* other);

  // implements Message ----------------------------------------------

  inline HelloRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  HelloRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HelloRequest& from);
  void MergeFrom(const HelloRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HelloRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string user = 1;
  bool has_user() const;
  void clear_user();
  static const int kUserFieldNumber = 1;
  const ::std::string& user() const;
  void set_user(const ::std::string& value);
  #if LANG_CXX11
  void set_user(::std::string&& value);
  #endif
  void set_user(const char* value);
  void set_user(const char* value, size_t size);
  ::std::string* mutable_user();
  ::std::string* release_user();
  void set_allocated_user(::std::string* user);

  // required string text = 2;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.HelloRequest)
 private:
  void set_has_user();
  void clear_has_user();
  void set_has_text();
  void clear_has_text();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr user_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  friend struct protobuf_main_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class HelloResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.HelloResponse) */ {
 public:
  HelloResponse();
  virtual ~HelloResponse();

  HelloResponse(const HelloResponse& from);

  inline HelloResponse& operator=(const HelloResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const HelloResponse& default_instance();

  static inline const HelloResponse* internal_default_instance() {
    return reinterpret_cast<const HelloResponse*>(
               &_HelloResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(HelloResponse* other);

  // implements Message ----------------------------------------------

  inline HelloResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  HelloResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const HelloResponse& from);
  void MergeFrom(const HelloResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(HelloResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string errmsg = 2;
  bool has_errmsg() const;
  void clear_errmsg();
  static const int kErrmsgFieldNumber = 2;
  const ::std::string& errmsg() const;
  void set_errmsg(const ::std::string& value);
  #if LANG_CXX11
  void set_errmsg(::std::string&& value);
  #endif
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  ::std::string* mutable_errmsg();
  ::std::string* release_errmsg();
  void set_allocated_errmsg(::std::string* errmsg);

  // required int32 retcode = 1;
  bool has_retcode() const;
  void clear_retcode();
  static const int kRetcodeFieldNumber = 1;
  ::google::protobuf::int32 retcode() const;
  void set_retcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.HelloResponse)
 private:
  void set_has_retcode();
  void clear_has_retcode();
  void set_has_errmsg();
  void clear_has_errmsg();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr errmsg_;
  ::google::protobuf::int32 retcode_;
  friend struct protobuf_main_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Conversation : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.Conversation) */ {
 public:
  Conversation();
  virtual ~Conversation();

  Conversation(const Conversation& from);

  inline Conversation& operator=(const Conversation& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Conversation& default_instance();

  static inline const Conversation* internal_default_instance() {
    return reinterpret_cast<const Conversation*>(
               &_Conversation_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(Conversation* other);

  // implements Message ----------------------------------------------

  inline Conversation* New() const PROTOBUF_FINAL { return New(NULL); }

  Conversation* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Conversation& from);
  void MergeFrom(const Conversation& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Conversation* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string topic = 1;
  bool has_topic() const;
  void clear_topic();
  static const int kTopicFieldNumber = 1;
  const ::std::string& topic() const;
  void set_topic(const ::std::string& value);
  #if LANG_CXX11
  void set_topic(::std::string&& value);
  #endif
  void set_topic(const char* value);
  void set_topic(const char* value, size_t size);
  ::std::string* mutable_topic();
  ::std::string* release_topic();
  void set_allocated_topic(::std::string* topic);

  // required string notice = 2;
  bool has_notice() const;
  void clear_notice();
  static const int kNoticeFieldNumber = 2;
  const ::std::string& notice() const;
  void set_notice(const ::std::string& value);
  #if LANG_CXX11
  void set_notice(::std::string&& value);
  #endif
  void set_notice(const char* value);
  void set_notice(const char* value, size_t size);
  ::std::string* mutable_notice();
  ::std::string* release_notice();
  void set_allocated_notice(::std::string* notice);

  // required string name = 3;
  bool has_name() const;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.Conversation)
 private:
  void set_has_topic();
  void clear_has_topic();
  void set_has_notice();
  void clear_has_notice();
  void set_has_name();
  void clear_has_name();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr topic_;
  ::google::protobuf::internal::ArenaStringPtr notice_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  friend struct protobuf_main_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConversationListRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.ConversationListRequest) */ {
 public:
  ConversationListRequest();
  virtual ~ConversationListRequest();

  ConversationListRequest(const ConversationListRequest& from);

  inline ConversationListRequest& operator=(const ConversationListRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConversationListRequest& default_instance();

  static inline const ConversationListRequest* internal_default_instance() {
    return reinterpret_cast<const ConversationListRequest*>(
               &_ConversationListRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(ConversationListRequest* other);

  // implements Message ----------------------------------------------

  inline ConversationListRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  ConversationListRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConversationListRequest& from);
  void MergeFrom(const ConversationListRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConversationListRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef ConversationListRequest_FilterType FilterType;
  static const FilterType DEFAULT =
    ConversationListRequest_FilterType_DEFAULT;
  static const FilterType ALL =
    ConversationListRequest_FilterType_ALL;
  static const FilterType NEAR_BY =
    ConversationListRequest_FilterType_NEAR_BY;
  static const FilterType FRIENDS =
    ConversationListRequest_FilterType_FRIENDS;
  static const FilterType HOT =
    ConversationListRequest_FilterType_HOT;
  static inline bool FilterType_IsValid(int value) {
    return ConversationListRequest_FilterType_IsValid(value);
  }
  static const FilterType FilterType_MIN =
    ConversationListRequest_FilterType_FilterType_MIN;
  static const FilterType FilterType_MAX =
    ConversationListRequest_FilterType_FilterType_MAX;
  static const int FilterType_ARRAYSIZE =
    ConversationListRequest_FilterType_FilterType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  FilterType_descriptor() {
    return ConversationListRequest_FilterType_descriptor();
  }
  static inline const ::std::string& FilterType_Name(FilterType value) {
    return ConversationListRequest_FilterType_Name(value);
  }
  static inline bool FilterType_Parse(const ::std::string& name,
      FilterType* value) {
    return ConversationListRequest_FilterType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string access_token = 1;
  bool has_access_token() const;
  void clear_access_token();
  static const int kAccessTokenFieldNumber = 1;
  const ::std::string& access_token() const;
  void set_access_token(const ::std::string& value);
  #if LANG_CXX11
  void set_access_token(::std::string&& value);
  #endif
  void set_access_token(const char* value);
  void set_access_token(const char* value, size_t size);
  ::std::string* mutable_access_token();
  ::std::string* release_access_token();
  void set_allocated_access_token(::std::string* access_token);

  // required int32 type = 2;
  bool has_type() const;
  void clear_type();
  static const int kTypeFieldNumber = 2;
  ::google::protobuf::int32 type() const;
  void set_type(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.ConversationListRequest)
 private:
  void set_has_access_token();
  void clear_has_access_token();
  void set_has_type();
  void clear_has_type();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr access_token_;
  ::google::protobuf::int32 type_;
  friend struct protobuf_main_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConversationListResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.tencent.mars.sample.proto.ConversationListResponse) */ {
 public:
  ConversationListResponse();
  virtual ~ConversationListResponse();

  ConversationListResponse(const ConversationListResponse& from);

  inline ConversationListResponse& operator=(const ConversationListResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConversationListResponse& default_instance();

  static inline const ConversationListResponse* internal_default_instance() {
    return reinterpret_cast<const ConversationListResponse*>(
               &_ConversationListResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ConversationListResponse* other);

  // implements Message ----------------------------------------------

  inline ConversationListResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  ConversationListResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConversationListResponse& from);
  void MergeFrom(const ConversationListResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConversationListResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .com.tencent.mars.sample.proto.Conversation list = 1;
  int list_size() const;
  void clear_list();
  static const int kListFieldNumber = 1;
  const ::com::tencent::mars::sample::proto::Conversation& list(int index) const;
  ::com::tencent::mars::sample::proto::Conversation* mutable_list(int index);
  ::com::tencent::mars::sample::proto::Conversation* add_list();
  ::google::protobuf::RepeatedPtrField< ::com::tencent::mars::sample::proto::Conversation >*
      mutable_list();
  const ::google::protobuf::RepeatedPtrField< ::com::tencent::mars::sample::proto::Conversation >&
      list() const;

  // @@protoc_insertion_point(class_scope:com.tencent.mars.sample.proto.ConversationListResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::com::tencent::mars::sample::proto::Conversation > list_;
  friend struct protobuf_main_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HelloRequest

// required string user = 1;
inline bool HelloRequest::has_user() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HelloRequest::set_has_user() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HelloRequest::clear_has_user() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HelloRequest::clear_user() {
  user_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_user();
}
inline const ::std::string& HelloRequest::user() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.HelloRequest.user)
  return user_.GetNoArena();
}
inline void HelloRequest::set_user(const ::std::string& value) {
  set_has_user();
  user_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.HelloRequest.user)
}
#if LANG_CXX11
inline void HelloRequest::set_user(::std::string&& value) {
  set_has_user();
  user_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.HelloRequest.user)
}
#endif
inline void HelloRequest::set_user(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_user();
  user_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.HelloRequest.user)
}
inline void HelloRequest::set_user(const char* value, size_t size) {
  set_has_user();
  user_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.HelloRequest.user)
}
inline ::std::string* HelloRequest::mutable_user() {
  set_has_user();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.HelloRequest.user)
  return user_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloRequest::release_user() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.HelloRequest.user)
  clear_has_user();
  return user_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloRequest::set_allocated_user(::std::string* user) {
  if (user != NULL) {
    set_has_user();
  } else {
    clear_has_user();
  }
  user_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), user);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.HelloRequest.user)
}

// required string text = 2;
inline bool HelloRequest::has_text() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HelloRequest::set_has_text() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HelloRequest::clear_has_text() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HelloRequest::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& HelloRequest::text() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.HelloRequest.text)
  return text_.GetNoArena();
}
inline void HelloRequest::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.HelloRequest.text)
}
#if LANG_CXX11
inline void HelloRequest::set_text(::std::string&& value) {
  set_has_text();
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.HelloRequest.text)
}
#endif
inline void HelloRequest::set_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.HelloRequest.text)
}
inline void HelloRequest::set_text(const char* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.HelloRequest.text)
}
inline ::std::string* HelloRequest::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.HelloRequest.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloRequest::release_text() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.HelloRequest.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloRequest::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.HelloRequest.text)
}

// -------------------------------------------------------------------

// HelloResponse

// required int32 retcode = 1;
inline bool HelloResponse::has_retcode() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void HelloResponse::set_has_retcode() {
  _has_bits_[0] |= 0x00000002u;
}
inline void HelloResponse::clear_has_retcode() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void HelloResponse::clear_retcode() {
  retcode_ = 0;
  clear_has_retcode();
}
inline ::google::protobuf::int32 HelloResponse::retcode() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.HelloResponse.retcode)
  return retcode_;
}
inline void HelloResponse::set_retcode(::google::protobuf::int32 value) {
  set_has_retcode();
  retcode_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.HelloResponse.retcode)
}

// optional string errmsg = 2;
inline bool HelloResponse::has_errmsg() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void HelloResponse::set_has_errmsg() {
  _has_bits_[0] |= 0x00000001u;
}
inline void HelloResponse::clear_has_errmsg() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void HelloResponse::clear_errmsg() {
  errmsg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_errmsg();
}
inline const ::std::string& HelloResponse::errmsg() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.HelloResponse.errmsg)
  return errmsg_.GetNoArena();
}
inline void HelloResponse::set_errmsg(const ::std::string& value) {
  set_has_errmsg();
  errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.HelloResponse.errmsg)
}
#if LANG_CXX11
inline void HelloResponse::set_errmsg(::std::string&& value) {
  set_has_errmsg();
  errmsg_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.HelloResponse.errmsg)
}
#endif
inline void HelloResponse::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_errmsg();
  errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.HelloResponse.errmsg)
}
inline void HelloResponse::set_errmsg(const char* value, size_t size) {
  set_has_errmsg();
  errmsg_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.HelloResponse.errmsg)
}
inline ::std::string* HelloResponse::mutable_errmsg() {
  set_has_errmsg();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.HelloResponse.errmsg)
  return errmsg_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HelloResponse::release_errmsg() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.HelloResponse.errmsg)
  clear_has_errmsg();
  return errmsg_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HelloResponse::set_allocated_errmsg(::std::string* errmsg) {
  if (errmsg != NULL) {
    set_has_errmsg();
  } else {
    clear_has_errmsg();
  }
  errmsg_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), errmsg);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.HelloResponse.errmsg)
}

// -------------------------------------------------------------------

// Conversation

// required string topic = 1;
inline bool Conversation::has_topic() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Conversation::set_has_topic() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Conversation::clear_has_topic() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Conversation::clear_topic() {
  topic_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_topic();
}
inline const ::std::string& Conversation::topic() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.Conversation.topic)
  return topic_.GetNoArena();
}
inline void Conversation::set_topic(const ::std::string& value) {
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.Conversation.topic)
}
#if LANG_CXX11
inline void Conversation::set_topic(::std::string&& value) {
  set_has_topic();
  topic_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.Conversation.topic)
}
#endif
inline void Conversation::set_topic(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.Conversation.topic)
}
inline void Conversation::set_topic(const char* value, size_t size) {
  set_has_topic();
  topic_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.Conversation.topic)
}
inline ::std::string* Conversation::mutable_topic() {
  set_has_topic();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.Conversation.topic)
  return topic_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Conversation::release_topic() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.Conversation.topic)
  clear_has_topic();
  return topic_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Conversation::set_allocated_topic(::std::string* topic) {
  if (topic != NULL) {
    set_has_topic();
  } else {
    clear_has_topic();
  }
  topic_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), topic);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.Conversation.topic)
}

// required string notice = 2;
inline bool Conversation::has_notice() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Conversation::set_has_notice() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Conversation::clear_has_notice() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Conversation::clear_notice() {
  notice_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_notice();
}
inline const ::std::string& Conversation::notice() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.Conversation.notice)
  return notice_.GetNoArena();
}
inline void Conversation::set_notice(const ::std::string& value) {
  set_has_notice();
  notice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.Conversation.notice)
}
#if LANG_CXX11
inline void Conversation::set_notice(::std::string&& value) {
  set_has_notice();
  notice_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.Conversation.notice)
}
#endif
inline void Conversation::set_notice(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_notice();
  notice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.Conversation.notice)
}
inline void Conversation::set_notice(const char* value, size_t size) {
  set_has_notice();
  notice_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.Conversation.notice)
}
inline ::std::string* Conversation::mutable_notice() {
  set_has_notice();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.Conversation.notice)
  return notice_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Conversation::release_notice() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.Conversation.notice)
  clear_has_notice();
  return notice_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Conversation::set_allocated_notice(::std::string* notice) {
  if (notice != NULL) {
    set_has_notice();
  } else {
    clear_has_notice();
  }
  notice_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), notice);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.Conversation.notice)
}

// required string name = 3;
inline bool Conversation::has_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Conversation::set_has_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Conversation::clear_has_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Conversation::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_name();
}
inline const ::std::string& Conversation::name() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.Conversation.name)
  return name_.GetNoArena();
}
inline void Conversation::set_name(const ::std::string& value) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.Conversation.name)
}
#if LANG_CXX11
inline void Conversation::set_name(::std::string&& value) {
  set_has_name();
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.Conversation.name)
}
#endif
inline void Conversation::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.Conversation.name)
}
inline void Conversation::set_name(const char* value, size_t size) {
  set_has_name();
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.Conversation.name)
}
inline ::std::string* Conversation::mutable_name() {
  set_has_name();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.Conversation.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Conversation::release_name() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.Conversation.name)
  clear_has_name();
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Conversation::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    set_has_name();
  } else {
    clear_has_name();
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.Conversation.name)
}

// -------------------------------------------------------------------

// ConversationListRequest

// required string access_token = 1;
inline bool ConversationListRequest::has_access_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConversationListRequest::set_has_access_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConversationListRequest::clear_has_access_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConversationListRequest::clear_access_token() {
  access_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_access_token();
}
inline const ::std::string& ConversationListRequest::access_token() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
  return access_token_.GetNoArena();
}
inline void ConversationListRequest::set_access_token(const ::std::string& value) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
}
#if LANG_CXX11
inline void ConversationListRequest::set_access_token(::std::string&& value) {
  set_has_access_token();
  access_token_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
}
#endif
inline void ConversationListRequest::set_access_token(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
}
inline void ConversationListRequest::set_access_token(const char* value, size_t size) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
}
inline ::std::string* ConversationListRequest::mutable_access_token() {
  set_has_access_token();
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
  return access_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConversationListRequest::release_access_token() {
  // @@protoc_insertion_point(field_release:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
  clear_has_access_token();
  return access_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConversationListRequest::set_allocated_access_token(::std::string* access_token) {
  if (access_token != NULL) {
    set_has_access_token();
  } else {
    clear_has_access_token();
  }
  access_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), access_token);
  // @@protoc_insertion_point(field_set_allocated:com.tencent.mars.sample.proto.ConversationListRequest.access_token)
}

// required int32 type = 2;
inline bool ConversationListRequest::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConversationListRequest::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConversationListRequest::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConversationListRequest::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::google::protobuf::int32 ConversationListRequest::type() const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.ConversationListRequest.type)
  return type_;
}
inline void ConversationListRequest::set_type(::google::protobuf::int32 value) {
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:com.tencent.mars.sample.proto.ConversationListRequest.type)
}

// -------------------------------------------------------------------

// ConversationListResponse

// repeated .com.tencent.mars.sample.proto.Conversation list = 1;
inline int ConversationListResponse::list_size() const {
  return list_.size();
}
inline void ConversationListResponse::clear_list() {
  list_.Clear();
}
inline const ::com::tencent::mars::sample::proto::Conversation& ConversationListResponse::list(int index) const {
  // @@protoc_insertion_point(field_get:com.tencent.mars.sample.proto.ConversationListResponse.list)
  return list_.Get(index);
}
inline ::com::tencent::mars::sample::proto::Conversation* ConversationListResponse::mutable_list(int index) {
  // @@protoc_insertion_point(field_mutable:com.tencent.mars.sample.proto.ConversationListResponse.list)
  return list_.Mutable(index);
}
inline ::com::tencent::mars::sample::proto::Conversation* ConversationListResponse::add_list() {
  // @@protoc_insertion_point(field_add:com.tencent.mars.sample.proto.ConversationListResponse.list)
  return list_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::com::tencent::mars::sample::proto::Conversation >*
ConversationListResponse::mutable_list() {
  // @@protoc_insertion_point(field_mutable_list:com.tencent.mars.sample.proto.ConversationListResponse.list)
  return &list_;
}
inline const ::google::protobuf::RepeatedPtrField< ::com::tencent::mars::sample::proto::Conversation >&
ConversationListResponse::list() const {
  // @@protoc_insertion_point(field_list:com.tencent.mars.sample.proto.ConversationListResponse.list)
  return list_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace proto
}  // namespace sample
}  // namespace mars
}  // namespace tencent
}  // namespace com

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::com::tencent::mars::sample::proto::ConversationListRequest_FilterType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::tencent::mars::sample::proto::ConversationListRequest_FilterType>() {
  return ::com::tencent::mars::sample::proto::ConversationListRequest_FilterType_descriptor();
}
template <> struct is_proto_enum< ::com::tencent::mars::sample::proto::CmdID> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::com::tencent::mars::sample::proto::CmdID>() {
  return ::com::tencent::mars::sample::proto::CmdID_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_main_2eproto__INCLUDED
