include $(IMPORT_LOCAL_PATH)/build.conf
include $(SELF_LOCAL_IMPORT_LIBRARIES_PATH)

#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ += $(SELF_LOCAL_IMPORT_LIBRARIES_PATH)

#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 20)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 19)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 18)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 17)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 16)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 15)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 14)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 13)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 12)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 11)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 10)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 9)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 8)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 7)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 6)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 5)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 4)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 3)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 2)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifeq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 1)
#__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(firstword $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#__SELF_LOCAL_IMPORT_LIBRARIES_PATH__ := $(wordlist 2,$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)),$(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__))
#include $(__FIRSTWORD__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)
#endif
#
#ifneq ($(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)), 0)
#$(error 'import_template.mk SELF_LOCAL_IMPORT_LIBRARIES_PATH count:$(words $(__SELF_LOCAL_IMPORT_LIBRARIES_PATH__)) too large!!!')
#endif
