// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.tencent.mars.sample.proto {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public static partial class MessagePush {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      #endregion
      #region Extensions
      internal static readonly object Descriptor;
      static MessagePush() {
        Descriptor = null;
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class MessagePush : pb::GeneratedMessageLite<MessagePush, MessagePush.Builder> {
    private MessagePush() { }
    private static readonly MessagePush defaultInstance = new MessagePush().MakeReadOnly();
    private static readonly string[] _messagePushFieldNames = new string[] { "content", "from", "topic" };
    private static readonly uint[] _messagePushFieldTags = new uint[] { 18, 26, 10 };
    public static MessagePush DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override MessagePush DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override MessagePush ThisMessage {
      get { return this; }
    }
    
    public const int TopicFieldNumber = 1;
    private bool hasTopic;
    private string topic_ = "";
    public string Topic {
      get { return topic_; }
    }
    
    public const int ContentFieldNumber = 2;
    private bool hasContent;
    private string content_ = "";
    public string Content {
      get { return content_; }
    }
    
    public const int FromFieldNumber = 3;
    private bool hasFrom;
    private string from_ = "";
    public string From {
      get { return from_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasTopic) return false;
        if (!hasContent) return false;
        if (!hasFrom) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _messagePushFieldNames;
      if (hasTopic) {
        output.WriteString(1, field_names[2], Topic);
      }
      if (hasContent) {
        output.WriteString(2, field_names[0], Content);
      }
      if (hasFrom) {
        output.WriteString(3, field_names[1], From);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(1, Topic);
        }
        if (hasContent) {
          size += pb::CodedOutputStream.ComputeStringSize(2, Content);
        }
        if (hasFrom) {
          size += pb::CodedOutputStream.ComputeStringSize(3, From);
        }
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      if (hasTopic) hash ^= topic_.GetHashCode();
      if (hasContent) hash ^= content_.GetHashCode();
      if (hasFrom) hash ^= from_.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      MessagePush other = obj as MessagePush;
      if (other == null) return false;
      if (hasTopic != other.hasTopic || (hasTopic && !topic_.Equals(other.topic_))) return false;
      if (hasContent != other.hasContent || (hasContent && !content_.Equals(other.content_))) return false;
      if (hasFrom != other.hasFrom || (hasFrom && !from_.Equals(other.from_))) return false;
      return true;
    }
    
    public override void PrintTo(global::System.IO.TextWriter writer) {
      PrintField("topic", hasTopic, topic_, writer);
      PrintField("content", hasContent, content_, writer);
      PrintField("from", hasFrom, from_, writer);
    }
    #endregion
    
    public static MessagePush ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    private MessagePush MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(MessagePush prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilderLite<MessagePush, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(MessagePush cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private MessagePush result;
      
      private MessagePush PrepareBuilder() {
        if (resultIsReadOnly) {
          MessagePush original = result;
          result = new MessagePush();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override MessagePush MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override MessagePush DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.MessagePush.DefaultInstance; }
      }
      
      public override MessagePush BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessageLite other) {
        if (other is MessagePush) {
          return MergeFrom((MessagePush) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(MessagePush other) {
      return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_messagePushFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _messagePushFieldTags[field_ordinal];
            else {
              ParseUnknownField(input, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                return this;
              }
              ParseUnknownField(input, extensionRegistry, tag, field_name);
              break;
            }
            case 10: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
            case 18: {
              result.hasContent = input.ReadString(ref result.content_);
              break;
            }
            case 26: {
              result.hasFrom = input.ReadString(ref result.from_);
              break;
            }
          }
        }
        
        return this;
        }
        
        
        public string Topic {
          get { return result.Topic; }
          set { SetTopic(value); }
        }
        public Builder SetTopic(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasTopic = true;
          result.topic_ = value;
          return this;
        }
        public Builder ClearTopic() {
          PrepareBuilder();
          result.hasTopic = false;
          result.topic_ = "";
          return this;
        }
        
        public string Content {
          get { return result.Content; }
          set { SetContent(value); }
        }
        public Builder SetContent(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasContent = true;
          result.content_ = value;
          return this;
        }
        public Builder ClearContent() {
          PrepareBuilder();
          result.hasContent = false;
          result.content_ = "";
          return this;
        }
        
        public string From {
          get { return result.From; }
          set { SetFrom(value); }
        }
        public Builder SetFrom(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasFrom = true;
          result.from_ = value;
          return this;
        }
        public Builder ClearFrom() {
          PrepareBuilder();
          result.hasFrom = false;
          result.from_ = "";
          return this;
        }
      }
      static MessagePush() {
        object.ReferenceEquals(global::com.tencent.mars.sample.proto.Proto.MessagePush.Descriptor, null);
      }
    }
    
    #endregion
    
  }
  
  #endregion Designer generated code
