// Generated by ProtoGen, Version=2.3.0.277, Culture=neutral, PublicKeyToken=17b3b1f090c3ea48.  DO NOT EDIT!
#pragma warning disable 1591, 0612
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace com.tencent.mars.sample.proto {
  
  namespace Proto {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public static partial class SendMessageResponse {
    
      #region Extension registration
      public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
      }
      #endregion
      #region Static variables
      #endregion
      #region Extensions
      internal static readonly object Descriptor;
      static SendMessageResponse() {
        Descriptor = null;
      }
      #endregion
      
    }
  }
  #region Messages
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
  public sealed partial class SendMessageResponse : pb::GeneratedMessageLite<SendMessageResponse, SendMessageResponse.Builder> {
    private SendMessageResponse() { }
    private static readonly SendMessageResponse defaultInstance = new SendMessageResponse().MakeReadOnly();
    private static readonly string[] _sendMessageResponseFieldNames = new string[] { "err_code", "err_msg", "from", "text", "topic" };
    private static readonly uint[] _sendMessageResponseFieldTags = new uint[] { 8, 18, 26, 34, 42 };
    public static SendMessageResponse DefaultInstance {
      get { return defaultInstance; }
    }
    
    public override SendMessageResponse DefaultInstanceForType {
      get { return DefaultInstance; }
    }
    
    protected override SendMessageResponse ThisMessage {
      get { return this; }
    }
    
    public const int ErrCodeFieldNumber = 1;
    private bool hasErrCode;
    private int errCode_;
    public int ErrCode {
      get { return errCode_; }
    }
    
    public const int ErrMsgFieldNumber = 2;
    private bool hasErrMsg;
    private string errMsg_ = "";
    public string ErrMsg {
      get { return errMsg_; }
    }
    
    public const int FromFieldNumber = 3;
    private bool hasFrom;
    private string from_ = "";
    public string From {
      get { return from_; }
    }
    
    public const int TextFieldNumber = 4;
    private bool hasText;
    private string text_ = "";
    public string Text {
      get { return text_; }
    }
    
    public const int TopicFieldNumber = 5;
    private bool hasTopic;
    private string topic_ = "";
    public string Topic {
      get { return topic_; }
    }
    
    public override bool IsInitialized {
      get {
        if (!hasErrCode) return false;
        if (!hasErrMsg) return false;
        if (!hasFrom) return false;
        if (!hasText) return false;
        if (!hasTopic) return false;
        return true;
      }
    }
    
    public override void WriteTo(pb::ICodedOutputStream output) {
      int size = SerializedSize;
      string[] field_names = _sendMessageResponseFieldNames;
      if (hasErrCode) {
        output.WriteInt32(1, field_names[0], ErrCode);
      }
      if (hasErrMsg) {
        output.WriteString(2, field_names[1], ErrMsg);
      }
      if (hasFrom) {
        output.WriteString(3, field_names[2], From);
      }
      if (hasText) {
        output.WriteString(4, field_names[3], Text);
      }
      if (hasTopic) {
        output.WriteString(5, field_names[4], Topic);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public override int SerializedSize {
      get {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasErrCode) {
          size += pb::CodedOutputStream.ComputeInt32Size(1, ErrCode);
        }
        if (hasErrMsg) {
          size += pb::CodedOutputStream.ComputeStringSize(2, ErrMsg);
        }
        if (hasFrom) {
          size += pb::CodedOutputStream.ComputeStringSize(3, From);
        }
        if (hasText) {
          size += pb::CodedOutputStream.ComputeStringSize(4, Text);
        }
        if (hasTopic) {
          size += pb::CodedOutputStream.ComputeStringSize(5, Topic);
        }
        memoizedSerializedSize = size;
        return size;
      }
    }
    
    #region Lite runtime methods
    public override int GetHashCode() {
      int hash = GetType().GetHashCode();
      if (hasErrCode) hash ^= errCode_.GetHashCode();
      if (hasErrMsg) hash ^= errMsg_.GetHashCode();
      if (hasFrom) hash ^= from_.GetHashCode();
      if (hasText) hash ^= text_.GetHashCode();
      if (hasTopic) hash ^= topic_.GetHashCode();
      return hash;
    }
    
    public override bool Equals(object obj) {
      SendMessageResponse other = obj as SendMessageResponse;
      if (other == null) return false;
      if (hasErrCode != other.hasErrCode || (hasErrCode && !errCode_.Equals(other.errCode_))) return false;
      if (hasErrMsg != other.hasErrMsg || (hasErrMsg && !errMsg_.Equals(other.errMsg_))) return false;
      if (hasFrom != other.hasFrom || (hasFrom && !from_.Equals(other.from_))) return false;
      if (hasText != other.hasText || (hasText && !text_.Equals(other.text_))) return false;
      if (hasTopic != other.hasTopic || (hasTopic && !topic_.Equals(other.topic_))) return false;
      return true;
    }
    
    public override void PrintTo(global::System.IO.TextWriter writer) {
      PrintField("err_code", hasErrCode, errCode_, writer);
      PrintField("err_msg", hasErrMsg, errMsg_, writer);
      PrintField("from", hasFrom, from_, writer);
      PrintField("text", hasText, text_, writer);
      PrintField("topic", hasTopic, topic_, writer);
    }
    #endregion
    
    public static SendMessageResponse ParseFrom(byte[] data) {
      return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
    }
    private SendMessageResponse MakeReadOnly() {
      return this;
    }
    
    public static Builder CreateBuilder() { return new Builder(); }
    public override Builder ToBuilder() { return CreateBuilder(this); }
    public override Builder CreateBuilderForType() { return new Builder(); }
    public static Builder CreateBuilder(SendMessageResponse prototype) {
      return new Builder(prototype);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ProtoGen", "2.3.0.277")]
    public sealed partial class Builder : pb::GeneratedBuilderLite<SendMessageResponse, Builder> {
      protected override Builder ThisBuilder {
        get { return this; }
      }
      public Builder() {
        result = DefaultInstance;
        resultIsReadOnly = true;
      }
      internal Builder(SendMessageResponse cloneFrom) {
        result = cloneFrom;
        resultIsReadOnly = true;
      }
      
      private bool resultIsReadOnly;
      private SendMessageResponse result;
      
      private SendMessageResponse PrepareBuilder() {
        if (resultIsReadOnly) {
          SendMessageResponse original = result;
          result = new SendMessageResponse();
          resultIsReadOnly = false;
          MergeFrom(original);
        }
        return result;
      }
      
      public override bool IsInitialized {
        get { return result.IsInitialized; }
      }
      
      protected override SendMessageResponse MessageBeingBuilt {
        get { return PrepareBuilder(); }
      }
      
      public override Builder Clear() {
        result = DefaultInstance;
        resultIsReadOnly = true;
        return this;
      }
      
      public override Builder Clone() {
        if (resultIsReadOnly) {
          return new Builder(result);
        } else {
          return new Builder().MergeFrom(result);
        }
      }
      
      public override SendMessageResponse DefaultInstanceForType {
        get { return global::com.tencent.mars.sample.proto.SendMessageResponse.DefaultInstance; }
      }
      
      public override SendMessageResponse BuildPartial() {
        if (resultIsReadOnly) {
          return result;
        }
        resultIsReadOnly = true;
        return result.MakeReadOnly();
      }
      
      public override Builder MergeFrom(pb::IMessageLite other) {
        if (other is SendMessageResponse) {
          return MergeFrom((SendMessageResponse) other);
        } else {
          base.MergeFrom(other);
          return this;
        }
      }
      
      public override Builder MergeFrom(SendMessageResponse other) {
      return this;
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input) {
        return MergeFrom(input, pb::ExtensionRegistry.Empty);
      }
      
      public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        PrepareBuilder();
        uint tag;
        string field_name;
        while (input.ReadTag(out tag, out field_name)) {
          if(tag == 0 && field_name != null) {
            int field_ordinal = global::System.Array.BinarySearch(_sendMessageResponseFieldNames, field_name, global::System.StringComparer.Ordinal);
            if(field_ordinal >= 0)
              tag = _sendMessageResponseFieldTags[field_ordinal];
            else {
              ParseUnknownField(input, extensionRegistry, tag, field_name);
              continue;
            }
          }
          switch (tag) {
            case 0: {
              throw pb::InvalidProtocolBufferException.InvalidTag();
            }
            default: {
              if (pb::WireFormat.IsEndGroupTag(tag)) {
                return this;
              }
              ParseUnknownField(input, extensionRegistry, tag, field_name);
              break;
            }
            case 8: {
              result.hasErrCode = input.ReadInt32(ref result.errCode_);
              break;
            }
            case 18: {
              result.hasErrMsg = input.ReadString(ref result.errMsg_);
              break;
            }
            case 26: {
              result.hasFrom = input.ReadString(ref result.from_);
              break;
            }
            case 34: {
              result.hasText = input.ReadString(ref result.text_);
              break;
            }
            case 42: {
              result.hasTopic = input.ReadString(ref result.topic_);
              break;
            }
          }
        }
        
        return this;
        }
        
        
        public int ErrCode {
          get { return result.ErrCode; }
          set { SetErrCode(value); }
        }
        public Builder SetErrCode(int value) {
          PrepareBuilder();
          result.hasErrCode = true;
          result.errCode_ = value;
          return this;
        }
        public Builder ClearErrCode() {
          PrepareBuilder();
          result.hasErrCode = false;
          result.errCode_ = 0;
          return this;
        }
        
        public string ErrMsg {
          get { return result.ErrMsg; }
          set { SetErrMsg(value); }
        }
        public Builder SetErrMsg(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasErrMsg = true;
          result.errMsg_ = value;
          return this;
        }
        public Builder ClearErrMsg() {
          PrepareBuilder();
          result.hasErrMsg = false;
          result.errMsg_ = "";
          return this;
        }
        
        public string From {
          get { return result.From; }
          set { SetFrom(value); }
        }
        public Builder SetFrom(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasFrom = true;
          result.from_ = value;
          return this;
        }
        public Builder ClearFrom() {
          PrepareBuilder();
          result.hasFrom = false;
          result.from_ = "";
          return this;
        }
        
        public string Text {
          get { return result.Text; }
          set { SetText(value); }
        }
        public Builder SetText(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasText = true;
          result.text_ = value;
          return this;
        }
        public Builder ClearText() {
          PrepareBuilder();
          result.hasText = false;
          result.text_ = "";
          return this;
        }
        
        public string Topic {
          get { return result.Topic; }
          set { SetTopic(value); }
        }
        public Builder SetTopic(string value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasTopic = true;
          result.topic_ = value;
          return this;
        }
        public Builder ClearTopic() {
          PrepareBuilder();
          result.hasTopic = false;
          result.topic_ = "";
          return this;
        }
      }
      static SendMessageResponse() {
        object.ReferenceEquals(global::com.tencent.mars.sample.proto.Proto.SendMessageResponse.Descriptor, null);
      }
    }
    
    #endregion
    
  }
  
  #endregion Designer generated code
