// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Conversation;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum CmdID

typedef GPB_ENUM(CmdID) {
  CmdID_CmdIdInvalid = -1,
  CmdID_CmdIdUnknown = 0,
  CmdID_CmdIdHello = 1,
  CmdID_CmdIdAuth = 2,
  CmdID_CmdIdSendMessage = 3,
  CmdID_CmdIdConversationList = 4,
  CmdID_CmdIdJointopic = 5,
  CmdID_CmdIdLefttopic = 7,
};

GPBEnumDescriptor *CmdID_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL CmdID_IsValidValue(int32_t value);

#pragma mark - Enum ConversationListRequest_FilterType

typedef GPB_ENUM(ConversationListRequest_FilterType) {
  ConversationListRequest_FilterType_Default = 0,
  ConversationListRequest_FilterType_All = 1,
  ConversationListRequest_FilterType_NearBy = 2,
  ConversationListRequest_FilterType_Friends = 3,
  ConversationListRequest_FilterType_Hot = 4,
};

GPBEnumDescriptor *ConversationListRequest_FilterType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ConversationListRequest_FilterType_IsValidValue(int32_t value);

#pragma mark - MainRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface MainRoot : GPBRootObject
@end

#pragma mark - HelloRequest

typedef GPB_ENUM(HelloRequest_FieldNumber) {
  HelloRequest_FieldNumber_User = 1,
  HelloRequest_FieldNumber_Text = 2,
};

@interface HelloRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@property(nonatomic, readwrite, copy, null_resettable) NSString *text;
/** Test to see if @c text has been set. */
@property(nonatomic, readwrite) BOOL hasText;

@end

#pragma mark - HelloResponse

typedef GPB_ENUM(HelloResponse_FieldNumber) {
  HelloResponse_FieldNumber_Retcode = 1,
  HelloResponse_FieldNumber_Errmsg = 2,
};

@interface HelloResponse : GPBMessage

@property(nonatomic, readwrite) int32_t retcode;

@property(nonatomic, readwrite) BOOL hasRetcode;
@property(nonatomic, readwrite, copy, null_resettable) NSString *errmsg;
/** Test to see if @c errmsg has been set. */
@property(nonatomic, readwrite) BOOL hasErrmsg;

@end

#pragma mark - Conversation

typedef GPB_ENUM(Conversation_FieldNumber) {
  Conversation_FieldNumber_Topic = 1,
  Conversation_FieldNumber_Notice = 2,
  Conversation_FieldNumber_Name = 3,
};

@interface Conversation : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *topic;
/** Test to see if @c topic has been set. */
@property(nonatomic, readwrite) BOOL hasTopic;

@property(nonatomic, readwrite, copy, null_resettable) NSString *notice;
/** Test to see if @c notice has been set. */
@property(nonatomic, readwrite) BOOL hasNotice;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;
/** Test to see if @c name has been set. */
@property(nonatomic, readwrite) BOOL hasName;

@end

#pragma mark - ConversationListRequest

typedef GPB_ENUM(ConversationListRequest_FieldNumber) {
  ConversationListRequest_FieldNumber_AccessToken = 1,
  ConversationListRequest_FieldNumber_Type = 2,
};

@interface ConversationListRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;
/** Test to see if @c accessToken has been set. */
@property(nonatomic, readwrite) BOOL hasAccessToken;

@property(nonatomic, readwrite) int32_t type;

@property(nonatomic, readwrite) BOOL hasType;
@end

#pragma mark - ConversationListResponse

typedef GPB_ENUM(ConversationListResponse_FieldNumber) {
  ConversationListResponse_FieldNumber_ListArray = 1,
};

@interface ConversationListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Conversation*> *listArray;
/** The number of items in @c listArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger listArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
