// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Person.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Person_PhoneNumber;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum Person_PhoneType

typedef GPB_ENUM(Person_PhoneType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  Person_PhoneType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  Person_PhoneType_Home = 0,
  Person_PhoneType_Mobile = 1,
  Person_PhoneType_Work = 2,
};

GPBEnumDescriptor *Person_PhoneType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL Person_PhoneType_IsValidValue(int32_t value);

#pragma mark - PersonRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface PersonRoot : GPBRootObject
@end

#pragma mark - Person

typedef GPB_ENUM(Person_FieldNumber) {
  Person_FieldNumber_Name = 1,
  Person_FieldNumber_UserId = 2,
  Person_FieldNumber_Email = 3,
  Person_FieldNumber_PhoneArray = 4,
};

@interface Person : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int32_t userId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Person_PhoneNumber*> *phoneArray;
/** The number of items in @c phoneArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger phoneArray_Count;

@end

#pragma mark - Person_PhoneNumber

typedef GPB_ENUM(Person_PhoneNumber_FieldNumber) {
  Person_PhoneNumber_FieldNumber_Number = 1,
  Person_PhoneNumber_FieldNumber_Type = 2,
};

@interface Person_PhoneNumber : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *number;

@property(nonatomic, readwrite) Person_PhoneType type;

@end

/**
 * Fetches the raw value of a @c Person_PhoneNumber's @c type property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Person_PhoneNumber_Type_RawValue(Person_PhoneNumber *message);
/**
 * Sets the raw value of an @c Person_PhoneNumber's @c type property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetPerson_PhoneNumber_Type_RawValue(Person_PhoneNumber *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
